spring:
  application:
    name: backend
  redis:
    host: localhost
    port: 6379

springdoc:
  api-docs:
    path: /api-docs  # OpenAPI 문서의 경로 설정
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI의 경로 설정

server:
  port: 8081